//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinerSplitter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JoinerSplitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Button_1 {
            get {
                return ResourceManager.GetString("Button_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split into groups.
        /// </summary>
        public static string Button_10 {
            get {
                return ResourceManager.GetString("Button_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Button_11 {
            get {
                return ResourceManager.GetString("Button_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_12 {
            get {
                return ResourceManager.GetString("Button_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek to the start of selection.
        /// </summary>
        public static string Button_2 {
            get {
                return ResourceManager.GetString("Button_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Start.
        /// </summary>
        public static string Button_3 {
            get {
                return ResourceManager.GetString("Button_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection End.
        /// </summary>
        public static string Button_4 {
            get {
                return ResourceManager.GetString("Button_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek to the end of selection.
        /// </summary>
        public static string Button_5 {
            get {
                return ResourceManager.GetString("Button_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Button_6 {
            get {
                return ResourceManager.GetString("Button_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add video.
        /// </summary>
        public static string Button_7 {
            get {
                return ResourceManager.GetString("Button_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move files up in group or to previous group.
        /// </summary>
        public static string Button_8 {
            get {
                return ResourceManager.GetString("Button_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move files down in group or to previous group.
        /// </summary>
        public static string Button_9 {
            get {
                return ResourceManager.GetString("Button_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original File.
        /// </summary>
        public static string GridViewColumn_1 {
            get {
                return ResourceManager.GetString("GridViewColumn_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string GridViewColumn_2 {
            get {
                return ResourceManager.GetString("GridViewColumn_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string GridViewColumn_3 {
            get {
                return ResourceManager.GetString("GridViewColumn_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuItem_1 {
            get {
                return ResourceManager.GetString("MenuItem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuItem_10 {
            get {
                return ResourceManager.GetString("MenuItem_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Video.
        /// </summary>
        public static string MenuItem_11 {
            get {
                return ResourceManager.GetString("MenuItem_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding _Presets.
        /// </summary>
        public static string MenuItem_12 {
            get {
                return ResourceManager.GetString("MenuItem_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New job.
        /// </summary>
        public static string MenuItem_2 {
            get {
                return ResourceManager.GetString("MenuItem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open job.
        /// </summary>
        public static string MenuItem_3 {
            get {
                return ResourceManager.GetString("MenuItem_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save job.
        /// </summary>
        public static string MenuItem_4 {
            get {
                return ResourceManager.GetString("MenuItem_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save job _As....
        /// </summary>
        public static string MenuItem_5 {
            get {
                return ResourceManager.GetString("MenuItem_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add video.
        /// </summary>
        public static string MenuItem_6 {
            get {
                return ResourceManager.GetString("MenuItem_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du_plicate.
        /// </summary>
        public static string MenuItem_7 {
            get {
                return ResourceManager.GetString("MenuItem_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string MenuItem_8 {
            get {
                return ResourceManager.GetString("MenuItem_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xport.
        /// </summary>
        public static string MenuItem_9 {
            get {
                return ResourceManager.GetString("MenuItem_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output folder first..
        /// </summary>
        public static string NeedOutputFolder {
            get {
                return ResourceManager.GetString("NeedOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file name.
        /// </summary>
        public static string OutputFilenameBox {
            get {
                return ResourceManager.GetString("OutputFilenameBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder.
        /// </summary>
        public static string OutputFolderBox {
            get {
                return ResourceManager.GetString("OutputFolderBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/stop video.
        /// </summary>
        public static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ProcessButton {
            get {
                return ResourceManager.GetString("ProcessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving video files details....
        /// </summary>
        public static string ReadingFile {
            get {
                return ResourceManager.GetString("ReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split selected cut to separate videos by current position.
        /// </summary>
        public static string SplitButton {
            get {
                return ResourceManager.GetString("SplitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: .
        /// </summary>
        public static string TextBlock_1 {
            get {
                return ResourceManager.GetString("TextBlock_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start: .
        /// </summary>
        public static string TextBlock_2 {
            get {
                return ResourceManager.GetString("TextBlock_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End: .
        /// </summary>
        public static string TextBlock_3 {
            get {
                return ResourceManager.GetString("TextBlock_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration: .
        /// </summary>
        public static string TextBlock_4 {
            get {
                return ResourceManager.GetString("TextBlock_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Do you want to save current job?.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved job.
        /// </summary>
        public static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
    }
}
